[project]
name = "rag-assignment"
version = "1.0.0"
description = "Simple RAG project"
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.1.2",
    "langchain-openai>=1.1.0",
    "python-dotenv>=1.2.1",
    "streamlit>=1.52.1",
    "weaviate-client>=4.18.3",
]

[project.optional-dependencies]
dev = [
    "ruff",
    "pre-commit",
]

[tool.uv]
dev-dependencies = [
    "ruff>=0.8.0",
    "pre-commit>=4.0.0",
]

[tool.ruff]
line-length = 119
target-version = "py313"

[tool.ruff.lint]
select = [
    "E",
    "F",
    "W",
    "I",
    "N",
    "UP",
    "B",
    "C4",
    "DJ",
]
ignore = [
    "E501",
]

[tool.ruff.lint.isort]
known-first-party = ["config", "core", "utils"]
